#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"

DOTBOT_BIN="dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

export CONFIG BASEDIR DOTBOT_BIN

## Running provision script 
scripts/provision_first_run

cd "${BASEDIR}"
