#!/bin/bash 

printf 'Downloading Setup...\n' >&2
wget -q https://apt.devkitpro.org/install-devkitpro-pacman \
    -O /tmp/install-devkitpro-pacman

printf 'Running Setup...\n'
chmod +x /tmp/install-devkitpro-pacman
sudo /tmp/install-devkitpro-pacman

rm -f /tmp/install-devkitpro-pacman