#!/bin/bash

source ./scripts/wait_process.sh


STATUSFILE=~/.local/share/.dotfiles/status

distro="$(lsb_release -i -s)"

function check_bin () {
    if [ -x "$(which $1)" ]; then
        return 0
    else
        printf '%s not found in $PATH.\n' ${1^} >&2 
        return 1
    fi
    
}


function install_omz () {
    ### Download from omz repo
    if [ -n "${ZSH}" ]; then 
        printf 'OMZ already installed...\n' >&2
        return 0
    fi
    
    printf 'Installing OMZ...\n' >&2

    wget -q "https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh"\
        -O /tmp/install.sh     
    bash /tmp/install.sh --unattended 
    rm /tmp/install.sh
    return 0
}

function setup_git_username(){
    if ! check_bin git; then 
        exit 2
    fi

    printf 'Configuring Git...\n' >&2
    git config --global user.email "${USER_EMAIL}"
    git config --global user.name "${USER_NAME}"

}

function install_packages_ubuntu (){

    local ubuntu_pkg_list=(
        'git' 'zsh' 'vim' 'curl'
        'python3' 'python3-pip' 
        'lastpass-cli' 'fzf'
    )

    sudo apt update -qq -y >/dev/null 2>&1 & 
    wait_process $! "Waiting for package update"

    printf 'Package list:\n' >&2
    printf ' * %s\n' "${ubuntu_pkg_list[@]}" >&2
    sudo apt install -qq -y "${ubuntu_pkg_list[@]}" >/dev/null 2>&1 & 
    wait_process $! "Installing packages"

    sudo pip install -U pip dotbot

}

function check_sudo () {
    
    ### Is root
    if [ "$(id -u)" = '0' ]; then 
        printf 'Already root proceeding...\n' >&2
        return 0
    fi

    printf 'Checking user permissions...\n' >&2
    ### Try to cache sudo credentials
    if ! sudo -v; then
        printf 'Not SuperUser, run as root or with sudoers allowed user\n' >&2
        exit 1
    fi

    printf 'Cached sudo credentials...\n' >&2
    return 0
}

function check_run_date (){
    if [ -r ~/.local/share/.dotfiles/status ]; then 
        STATUS=$(<${STATUSFILE})
        return 0
    fi 
    return 1
}

function run_dotbot () {
    local dotbot_path="$(which ${DOTBOT_BIN})"

    if ! [ -x "${dotbot_path}" ]; then 
       printf 'Dotbot not found.\n' "${dotbot_path}" >&2
       return 1
    fi 


    pushd "${BASEDIR}"

    printf 'Running dotbot: %s\n' "${dotbot_path}" >&2
    "${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}"

    popd
    return 0
}


function main () {

    if check_run_date; then
        printf 'Already provioned\n'
        if [ -n "${STATUS}" ]; then
            run_dotbot
            printf -- 'Provisioned at %s\n' "$(date +"%D - %T" -d"${STATUS}")"
        fi
        return 0
    fi

    check_sudo

    ### Running installer
    if [ "${distro}" = 'Ubuntu' ];then
        install_packages_ubuntu
    fi
    
    setup_git_username
    install_omz

    mkdir -p ~/.local/share/.dotfiles/
    date +"@%s" > ~/.local/share/.dotfiles/status

    run_dotbot 

    ### Running zsh if everything is OK
    if check_bin zsh; then
        printf 'Iniciando ZSH:%s\n' "zsh"
        zsh
    fi

}

if [ "$(basename -- "$0")" = 'provision_first_run' ]; then 
    main "$@"
    exit 0 
fi
